// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5EaziNpzG2LQXJ9XBWGOKvZF8il3BUwo',
    appId: '1:57261079447:web:fe6ccf0d0090d6abfca2d2',
    messagingSenderId: '57261079447',
    projectId: 'splitnest-23d84',
    authDomain: 'splitnest-23d84.firebaseapp.com',
    storageBucket: 'splitnest-23d84.firebasestorage.app',
    measurementId: 'G-1C0V7WD7V2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmK2PTiE_7ClrwhC9wyvudZpOTdUuXuts',
    appId: '1:57261079447:android:3723f5ed49b76b80fca2d2',
    messagingSenderId: '57261079447',
    projectId: 'splitnest-23d84',
    storageBucket: 'splitnest-23d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAWkUjnctEGzbXKdgyMH_XHd7PSg3eYr0',
    appId: '1:57261079447:ios:dd2758eb1d60a424fca2d2',
    messagingSenderId: '57261079447',
    projectId: 'splitnest-23d84',
    storageBucket: 'splitnest-23d84.firebasestorage.app',
    iosClientId: '57261079447-3qh3soum68uc9ag00oi366b3ngnt367h.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAWkUjnctEGzbXKdgyMH_XHd7PSg3eYr0',
    appId: '1:57261079447:ios:dd2758eb1d60a424fca2d2',
    messagingSenderId: '57261079447',
    projectId: 'splitnest-23d84',
    storageBucket: 'splitnest-23d84.firebasestorage.app',
    iosClientId: '57261079447-3qh3soum68uc9ag00oi366b3ngnt367h.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5EaziNpzG2LQXJ9XBWGOKvZF8il3BUwo',
    appId: '1:57261079447:web:a59194cd1a58a34efca2d2',
    messagingSenderId: '57261079447',
    projectId: 'splitnest-23d84',
    authDomain: 'splitnest-23d84.firebaseapp.com',
    storageBucket: 'splitnest-23d84.firebasestorage.app',
    measurementId: 'G-R31B8TGJ8B',
  );
}
